from .dialog_combo_ui import Ui_dialog_combo as UiDialogCombo
from .dialog_config_ui import Ui_dialog_config as UIDialogConfig
from .dialog_multiple_choice_ui import Ui_dialog_multiple_choice as UIDialogMultipleChoice
from .form_anova_ui import Ui_form_anova as UIFormANOVA
from .form_boxplot_ui import Ui_form_boxplot as UIFormBoxplot
from .form_generate_ui import Ui_form_generate as UIFormGenerate
from .form_log_process_ui import Ui_form_log_process as UIFormLogProcess
from .form_message_logging_ui import Ui_form_message_logging as UIFormMessageLogging
from .form_metrics_ui import Ui_form_metrics as UIFormMetrics
from .form_scatter_ui import Ui_form_scatter as UIFormScatter
from .form_spearmanr_ui import Ui_form_spearmanr as UIFormSpearmanr
from .main_window_ui import Ui_main_window as UIMainWindow
from .widget_labeled_edit_ui import Ui_LabeledEdit as UILabeledEdit
