# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(282, 345)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.text_first = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_first.setGeometry(QtCore.QRect(80, 50, 131, 31))
        self.text_first.setObjectName("text_first")
        self.text_result = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_result.setGeometry(QtCore.QRect(80, 180, 131, 31))
        self.text_result.setObjectName("text_result")
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setGeometry(QtCore.QRect(80, 140, 131, 25))
        self.button_plus.setObjectName("button_plus")
        self.text_second = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.text_second.setGeometry(QtCore.QRect(80, 90, 131, 31))
        self.text_second.setObjectName("text_second")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 282, 28))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "PyQt5-Demo"))
        self.text_first.setPlaceholderText(_translate("main_window", "a"))
        self.text_result.setPlaceholderText(_translate("main_window", "resulf of a + b"))
        self.button_plus.setText(_translate("main_window", "PushButton"))
        self.text_second.setPlaceholderText(_translate("main_window", "b"))
